### ISSUE TITLE
Error when trying to import Expression in Playground

### ISSUE THREAD

**Issue by PopFlamingo** [mpangburn/Expressions#3]
Amazing project it's beautiful !
I just had a little issue where Xcode (9.2) wasn't able to run the playground due to an error when trying to `import Expression`, changing the name of the playground solves the issue apparently (other people on SO have similar issues).

**Comment by mpangburn** [comment]
I've experienced the same issue, and I'm afraid [the Playground name isn't the bug](https://i.imgur.com/2ZlLzcN.png). The other related bug is "Can't find Expression_Sources" (#4). I searched for a long time to find a real solution for these without success, but I can offer a temporary solution:

1. In AnimationEvaluation.swift (located in the Sources folder of Expression.xcplayground), comment out the `import Expression` line.
2. Return to a Playground page and allow compilation of the Sources to fail. You may not get any error message in the console, but you should see the little red Xcode failure icon at the top of the screen (likely with the number 3 on it).
3. Return to AnimateEvaluation.swift and uncomment the `import Expression` line.
4. Return to the Playground pages--they should now function.

I'll be continuing to look for the cause of these problems, but I'm afraid for the time being we'll have to make do with this workaround.

**Comment by PopFlamingo** [comment]
Did you encounter the issue even after renaming the playground ? Renaming the playground fixed it for me but Xcode is indeed quite buggy : the playground was sometimes working and sometimes not before I renamed it...

Trevör

**Comment by mpangburn** [comment]
Yes, the issue persists for me even when renaming the Playground--can you consistently open the .xcworkspace file and run the Playground pages without errors after renaming?

**Comment by PopFlamingo** [comment]
I hadn't relaunched Xcode, now that I did the issue is back ! 😕
Hope that Apple will fix this soon...

**Comment by NathanJozef** [comment]
Unfortunately even following your temporary workaround the issue is persisting on my machine. If I have time I shall see if I can fix it.

Otherwise, I'll keep checking. 

A wonderful looking project though.
